/*******************************************************************************
 * Copyright 2012
 * Ubiquitous Knowledge Processing (UKP) Lab
 * Technische Universität Darmstadt
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package org.dkpro.jowkl.api;

import java.util.HashMap;

/**
 * Holds Language Constants, that are used in OW DataBase
 *
 * @author matuschek
 *
 */
public class OWLanguage {
	static HashMap<Integer, String> languageNames = new HashMap<Integer, String>();
	public static final int  Bulgarian=84;
	public static final int  English=85;
	public static final int  French=86;
	public static final int  Castilian=87;
	public static final int  Russian=88;
	public static final int  Dutch=89;
	public static final int  Czech=90;
	public static final int  Swedish=91;
	public static final int  Slovenian=92;
	public static final int  Polish=93;
	public static final int  Portuguese=94;
	public static final int  Bokmål=95;
	public static final int  Basque=96;
	public static final int  Slovak=97;
	public static final int  Estonian=98;
	public static final int  Finnish=99;
	public static final int  Italian=100;
	public static final int  German=101;
	public static final int  Hungarian=102;
	public static final int  Danish=103;
	public static final int  English_United_States=104;
	public static final int  Greek=105;
	public static final int  Hebrew=106;
	public static final int  Mandarin_simplified=107;
	public static final int  Neapolitan=109;
	public static final int  Marathi=110;
	public static final int  Lombard=111;
	public static final int  Japanese=112;
	public static final int  Esperanto=113;
	public static final int  Piedmontese=114;
	public static final int  Venetian=115;
	public static final int  Ukrainian=116;
	public static final int  Catalan=117;
	public static final int  Ewe=118;
	public static final int  Akan=119;
	public static final int  Arabic=120;
	public static final int  Hausa_Ajami=121;
	public static final int  Hausa_Latin=122;
	public static final int  Armenian=123;
	public static final int  Georgian=124;
	public static final int  Afrikaans=125;
	public static final int  French_Canada=126;
	public static final int  French_Switzerland=127;
	public static final int  Serbian_Cyrillic_script=128;
	public static final int  Serbian_Latin_script=129;
	public static final int  Thai=130;
	public static final int  Ido=131;
	public static final int  Romanian=133;
	public static final int  Kölsch=134;
	public static final int  Mandarin_traditional=135;
	public static final int  English_United_Kingdom=136;
	public static final int  Turkish=137;
	public static final int  Korean=138;
	public static final int  Khmer=139;
	public static final int  Sicilian=140;
	public static final int  Aragonese=141;
	public static final int  Persian=142;
	public static final int  Latvian=143;
	public static final int  Vietnamese=144;
	public static final int  Swahili=145;
	public static final int  Bavarian=146;
	public static final int  Belarusian=147;
	public static final int  Kashubian=148;
	public static final int  Croatian=149;
	public static final int  Lithuanian=150;
	public static final int  Cantonese=151;
	public static final int  Tajik=152;
	public static final int  Welsh=153;
	public static final int  Bambara=154;
	public static final int  Portuguese_Brazil=155;
	public static final int  Portuguese_Portugal=156;
	public static final int  Telugu=158;
	public static final int  Gilaki=159;
	public static final int  Eastern_Mari=160;
	public static final int  Western_Mari=161;
	public static final int  Gujarati=162;
	public static final int  Hindi=163;
	public static final int  Tamil=164;
	public static final int  Indonesian=165;
	public static final int  Irish=166;
	public static final int  French_Belgium=167;
	public static final int  Limburgish=168;
	public static final int  Alemannic_German=169;
	public static final int  Marwari=170;
	public static final int  Sranan=171;
	public static final int  German_Austria=172;
	public static final int  German_Switzerland=173;
	public static final int  Ancient_Greek=174;
	public static final int  Mycenaean_Greek=175;
	public static final int  Cappadocian_Greek=176;
	public static final int  Tosk=177;
	public static final int  Gheg=178;
	public static final int  Arvanitic=179;
	public static final int  Arbëreshë_Albanian=180;
	public static final int  Kannada=181;
	public static final int  Breton=182;
	public static final int  Frisian=183;
	public static final int  Navajo=184;
	public static final int  Bengali=185;
	public static final int  Urdu=186;
	public static final int  French_France=187;
	public static final int  Nepali=188;
	public static final int  Igbo=189;
	public static final int  Ladin=190;
	public static final int  Kazakh=191;
	public static final int  Walloon=192;
	public static final int  Icelandic=193;
	public static final int  Tatar=194;
	public static final int  Asturian=195;
	public static final int  Sindhi_Arabic_script=196;
	public static final int  Sindhi_Gurumukhi_script=197;
	public static final int  Yoruba=198;
	public static final int  Galician=199;
	public static final int  Nynorsk=200;
	public static final int  Lingala=202;
	public static final int  Xhosa=203;
	public static final int  Upper_Sorbian=204;
	public static final int  Lower_Sorbian=205;
	public static final int  Tagalog=206;
	public static final int  Maltese=207;
	public static final int  Cebuano=208;
	public static final int  Macedonian=209;
	public static final int  Interlingua=210;
	public static final int  Interlingue=211;
	public static final int  Faroese=213;
	public static final int  Zulu=214;
	public static final int  Sanskrit=215;
	public static final int  Nepal_Bhasa=216;
	public static final int  Malayalam=217;
	public static final int  Flemish=218;
	public static final int  Chickasaw=219;
	public static final int  Corsican=220;
	public static final int  Volapük=221;
	public static final int  Malay=222;
	public static final int  Kabyle=223;
	public static final int  Manx=224;
	public static final int  Ossetian=225;
	public static final int  Crimean_Tatar=226;
	public static final int  Bashkir=227;
	public static final int  Cherokee=228;
	public static final int  Kyrgyz=229;
	public static final int  Kiribati=230;
	public static final int  Javanese=231;
	public static final int  Extremaduran=232;
	public static final int  Tetum=233;
	public static final int  Mirandese=234;
	public static final int  Emiliano_Romagnolo=235;
	public static final int  Wolof=236;
	public static final int  Somali=237;
	public static final int  Latin=238;
	public static final int  Novial=239;
	public static final int  Eastern_Yiddish=240;
	public static final int  Pitjantjatjara=241;
	public static final int  Lojban=242;
	public static final int  Luxembourgish=243;
	public static final int  Romansch=244;
	public static final int  Mingrelian=245;
	public static final int  Maori=246;
	public static final int  Kara_Kalpak=247;
	public static final int  Divehi=248;
	public static final int  Assamese=249;
	public static final int  Abkhaz=250;
	public static final int  Kotava=251;
	public static final int  Sundanese=252;
	public static final int  Cornish=253;
	public static final int  Pennsylvania_Deitsch=254;
	public static final int  Comorian=255;
	public static final int  Saterfriesisch=256;
	public static final int  Luganda=257;
	public static final int  Sinhala=258;
	public static final int  Bishnupriya=259;
	public static final int  Central_Kurdish=260;
	public static final int  Tigrigna=261;
	public static final int  Scottish_Gaelic=262;
	public static final int  Old_English=263;
	public static final int  Dzongkha=264;
	public static final int  Lingua_Franca_Nova=265;
	public static final int  Nhengatu=266;
	public static final int  Silesian=267;
	public static final int  Megleno_Romanian=268;
	public static final int  Ingush=269;
	public static final int  Southern_Balochi=270;
	public static final int  Erzya=271;
	public static final int  Lao=272;
	public static final int  Occitan=273;
	public static final int  Ligurian=274;
	public static final int  Burmese=275;
	public static final int  Amharic=276;
	public static final int  Moksha=277;
	public static final int  Ilokano=278;
	public static final int  Chuvash=279;
	public static final int  Samoan=280;
	public static final int  Udmurt=281;
	public static final int  Tok_Pisin=282;
	public static final int  Franco_Provençal=283;
	public static final int  Scots=284;
	public static final int  Wymysorys=285;
	public static final int  Hawaiian=286;
	public static final int  Chechen=287;
	public static final int  Bosnian=288;
	public static final int  Tongan=289;
	public static final int  Bakhtiari=290;
	public static final int  Pontic=291;
	public static final int  Egyptian_Arabic=292;
	public static final int  Picard=293;
	public static final int  South_Saami=294;
	public static final int  Võro=295;
	public static final int  Kiche=296;
	public static final int  Tabasco_Chontal=297;
	public static final int  Chol=298;
	public static final int  Chorti=299;
	public static final int  Tzeltal=300;
	public static final int  Tzotzil=301;
	public static final int  Chicomuceltec=302;
	public static final int  Huastec=303;
	public static final int  Chuj=304;
	public static final int  Tojolabal=305;
	public static final int  Jakalteko=306;
	public static final int  Kanjobal=307;
	public static final int  Akateko=308;
	public static final int  Mocho=309;
	public static final int  Awakateko=310;
	public static final int  Ixil=311;
	public static final int  Mam=312;
	public static final int  Tektiteko=313;
	public static final int  Kekchí=314;
	public static final int  Poqomam=315;
	public static final int  Poqomchi=316;
	public static final int  Kaqchikel=317;
	public static final int  Achi=318;
	public static final int  Tzutujil=319;
	public static final int  Sacapulteco=320;
	public static final int  Sipacapense=321;
	public static final int  Uspanteco=322;
	public static final int  Mopán_Maya=323;
	public static final int  Lacandon=324;
	public static final int  Yucatán_Maya=325;
	public static final int  Middle_High_German=327;
	public static final int  Old_High_German=328;
	public static final int  Mongolian=329;
	public static final int  Aceh=330;
	public static final int  Rapa_Nui=331;
	public static final int  Old_French=332;
	public static final int  Middle_French=333;
	public static final int  Haitian_Creole_French=334;
	public static final int  Church_Slavic=335;
	public static final int  Latgalian=336;
	public static final int  Aramaic_Official_Hebrew=337;
	public static final int  Aramaic_Jewish_Palestinian=338;
	public static final int  Classical_Syriac=339;
	public static final int  Jewish_Babylonian_Aramaic=340;
	public static final int  Hiligaynon=341;
	public static final int  Old_Irish=342;
	public static final int  Karachay_Balkar=343;
	public static final int  Réunion_Creole=344;
	public static final int  Benga=345;
	public static final int  Punu=346;
	public static final int  Mpongwe=347;
	public static final int  Kélé=348;
	public static final int  Chewa=349;
	public static final int  Bemba=350;
	public static final int  Umbundu=351;
	public static final int  Lunda=352;
	public static final int  Tonga=353;
	public static final int  Albanian=354;
	public static final int  Sesotho=355;
	public static final int  Kalaallisut=356;
	public static final int  Northern_Kurdish=357;
	public static final int  Kabuverdianu=358;
	public static final int  Ugaritic=359;
	public static final int  Vlax_Romani=360;
	public static final int  Classical_Armenian=361;
	public static final int  Ottoman_Turkish=362;
	public static final int  Abi=363;
	public static final int  Araki=364;
	public static final int  Bislama=365;
	public static final int  Fon=366;
	public static final int  Futunan=367;
	public static final int  International=368;
	public static final int  Holikachuk=369;
	public static final int  Uzbek=370;
	public static final int  Anglo_Norman=371;
	public static final int  Bainouk_Gunyaamolo=372;
	public static final int  Greek_Ancient_Egypt=373;
	public static final int  Malagasy=374;
	public static final int  Tsimihety_Malagasy=375;

	/**
	 * Helper function for quickly retrieving languages
	 *
	 * @param i language code
	 * @return name of the language
	 */

	public static String getName(int i)
	{
		languageNames.put(84, "Bulgarian");
		languageNames.put(85, "English");
		languageNames.put(86, "French");
		languageNames.put(87, "Castilian");
		languageNames.put(88, "Russian");
		languageNames.put(89, "Dutch");
		languageNames.put(90, "Czech");
		languageNames.put(91, "Swedish");
		languageNames.put(92, "Slovenian");
		languageNames.put(93, "Polish");
		languageNames.put(94, "Portuguese");
		languageNames.put(95, "Bokmål");
		languageNames.put(96, "Basque");
		languageNames.put(97, "Slovak");
		languageNames.put(98, "Estonian");
		languageNames.put(99, "Finnish");
		languageNames.put(100, "Italian");
		languageNames.put(101, "German");
		languageNames.put(102, "Hungarian");
		languageNames.put(103, "Danish");
		languageNames.put(104, "English_United_States");
		languageNames.put(105, "Greek");
		languageNames.put(106, "Hebrew");
		languageNames.put(107, "Mandarin_simplified");
		languageNames.put(109, "Neapolitan");
		languageNames.put(110, "Marathi");
		languageNames.put(111, "Lombard");
		languageNames.put(112, "Japanese");
		languageNames.put(113, "Esperanto");
		languageNames.put(114, "Piedmontese");
		languageNames.put(115, "Venetian");
		languageNames.put(116, "Ukrainian");
		languageNames.put(117, "Catalan");
		languageNames.put(118, "Ewe");
		languageNames.put(119, "Akan");
		languageNames.put(120, "Arabic");
		languageNames.put(121, "Hausa_Ajami");
		languageNames.put(122, "Hausa_Latin");
		languageNames.put(123, "Armenian");
		languageNames.put(124, "Georgian");
		languageNames.put(125, "Afrikaans");
		languageNames.put(126, "French_Canada");
		languageNames.put(127, "French_Switzerland");
		languageNames.put(128, "Serbian_Cyrillic_script");
		languageNames.put(129, "Serbian_Latin_script");
		languageNames.put(130, "Thai");
		languageNames.put(131, "Ido");
		languageNames.put(133, "Romanian");
		languageNames.put(134, "Kölsch");
		languageNames.put(135, "Mandarin_traditional");
		languageNames.put(136, "English_United_Kingdom");
		languageNames.put(137, "Turkish");
		languageNames.put(138, "Korean");
		languageNames.put(139, "Khmer");
		languageNames.put(140, "Sicilian");
		languageNames.put(141, "Aragonese");
		languageNames.put(142, "Persian");
		languageNames.put(143, "Latvian");
		languageNames.put(144, "Vietnamese");
		languageNames.put(145, "Swahili");
		languageNames.put(146, "Bavarian");
		languageNames.put(147, "Belarusian");
		languageNames.put(148, "Kashubian");
		languageNames.put(149, "Croatian");
		languageNames.put(150, "Lithuanian");
		languageNames.put(151, "Cantonese");
		languageNames.put(152, "Tajik");
		languageNames.put(153, "Welsh");
		languageNames.put(154, "Bambara");
		languageNames.put(155, "Portuguese_Brazil");
		languageNames.put(156, "Portuguese_Portugal");
		languageNames.put(158, "Telugu");
		languageNames.put(159, "Gilaki");
		languageNames.put(160, "Eastern_Mari");
		languageNames.put(161, "Western_Mari");
		languageNames.put(162, "Gujarati");
		languageNames.put(163, "Hindi");
		languageNames.put(164, "Tamil");
		languageNames.put(165, "Indonesian");
		languageNames.put(166, "Irish");
		languageNames.put(167, "French_Belgium");
		languageNames.put(168, "Limburgish");
		languageNames.put(169, "Alemannic_German");
		languageNames.put(170, "Marwari");
		languageNames.put(171, "Sranan");
		languageNames.put(172, "German_Austria");
		languageNames.put(173, "German_Switzerland");
		languageNames.put(174, "Ancient_Greek");
		languageNames.put(175, "Mycenaean_Greek");
		languageNames.put(176, "Cappadocian_Greek");
		languageNames.put(177, "Tosk");
		languageNames.put(178, "Gheg");
		languageNames.put(179, "Arvanitic");
		languageNames.put(180, "Arbëreshë_Albanian");
		languageNames.put(181, "Kannada");
		languageNames.put(182, "Breton");
		languageNames.put(183, "Frisian");
		languageNames.put(184, "Navajo");
		languageNames.put(185, "Bengali");
		languageNames.put(186, "Urdu");
		languageNames.put(187, "French_France");
		languageNames.put(188, "Nepali");
		languageNames.put(189, "Igbo");
		languageNames.put(190, "Ladin");
		languageNames.put(191, "Kazakh");
		languageNames.put(192, "Walloon");
		languageNames.put(193, "Icelandic");
		languageNames.put(194, "Tatar");
		languageNames.put(195, "Asturian");
		languageNames.put(196, "Sindhi_Arabic_script");
		languageNames.put(197, "Sindhi_Gurumukhi_script");
		languageNames.put(198, "Yoruba");
		languageNames.put(199, "Galician");
		languageNames.put(200, "Nynorsk");
		languageNames.put(202, "Lingala");
		languageNames.put(203, "Xhosa");
		languageNames.put(204, "Upper_Sorbian");
		languageNames.put(205, "Lower_Sorbian");
		languageNames.put(206, "Tagalog");
		languageNames.put(207, "Maltese");
		languageNames.put(208, "Cebuano");
		languageNames.put(209, "Macedonian");
		languageNames.put(210, "Interlingua");
		languageNames.put(211, "Interlingue");
		languageNames.put(213, "Faroese");
		languageNames.put(214, "Zulu");
		languageNames.put(215, "Sanskrit");
		languageNames.put(216, "Nepal_Bhasa");
		languageNames.put(217, "Malayalam");
		languageNames.put(218, "Flemish");
		languageNames.put(219, "Chickasaw");
		languageNames.put(220, "Corsican");
		languageNames.put(221, "Volapük");
		languageNames.put(222, "Malay");
		languageNames.put(223, "Kabyle");
		languageNames.put(224, "Manx");
		languageNames.put(225, "Ossetian");
		languageNames.put(226, "Crimean_Tatar");
		languageNames.put(227, "Bashkir");
		languageNames.put(228, "Cherokee");
		languageNames.put(229, "Kyrgyz");
		languageNames.put(230, "Kiribati");
		languageNames.put(231, "Javanese");
		languageNames.put(232, "Extremaduran");
		languageNames.put(233, "Tetum");
		languageNames.put(234, "Mirandese");
		languageNames.put(235, "Emiliano_Romagnolo");
		languageNames.put(236, "Wolof");
		languageNames.put(237, "Somali");
		languageNames.put(238, "Latin");
		languageNames.put(239, "Novial");
		languageNames.put(240, "Eastern_Yiddish");
		languageNames.put(241, "Pitjantjatjara");
		languageNames.put(242, "Lojban");
		languageNames.put(243, "Luxembourgish");
		languageNames.put(244, "Romansch");
		languageNames.put(245, "Mingrelian");
		languageNames.put(246, "Maori");
		languageNames.put(247, "Kara_Kalpak");
		languageNames.put(248, "Divehi");
		languageNames.put(249, "Assamese");
		languageNames.put(250, "Abkhaz");
		languageNames.put(251, "Kotava");
		languageNames.put(252, "Sundanese");
		languageNames.put(253, "Cornish");
		languageNames.put(254, "Pennsylvania_Deitsch");
		languageNames.put(255, "Comorian");
		languageNames.put(256, "Saterfriesisch");
		languageNames.put(257, "Luganda");
		languageNames.put(258, "Sinhala");
		languageNames.put(259, "Bishnupriya");
		languageNames.put(260, "Central_Kurdish");
		languageNames.put(261, "Tigrigna");
		languageNames.put(262, "Scottish_Gaelic");
		languageNames.put(263, "Old_English");
		languageNames.put(264, "Dzongkha");
		languageNames.put(265, "Lingua_Franca_Nova");
		languageNames.put(266, "Nhengatu");
		languageNames.put(267, "Silesian");
		languageNames.put(268, "Megleno_Romanian");
		languageNames.put(269, "Ingush");
		languageNames.put(270, "Southern_Balochi");
		languageNames.put(271, "Erzya");
		languageNames.put(272, "Lao");
		languageNames.put(273, "Occitan");
		languageNames.put(274, "Ligurian");
		languageNames.put(275, "Burmese");
		languageNames.put(276, "Amharic");
		languageNames.put(277, "Moksha");
		languageNames.put(278, "Ilokano");
		languageNames.put(279, "Chuvash");
		languageNames.put(280, "Samoan");
		languageNames.put(281, "Udmurt");
		languageNames.put(282, "Tok_Pisin");
		languageNames.put(283, "Franco_Provençal");
		languageNames.put(284, "Scots");
		languageNames.put(285, "Wymysorys");
		languageNames.put(286, "Hawaiian");
		languageNames.put(287, "Chechen");
		languageNames.put(288, "Bosnian");
		languageNames.put(289, "Tongan");
		languageNames.put(290, "Bakhtiari");
		languageNames.put(291, "Pontic");
		languageNames.put(292, "Egyptian_Arabic");
		languageNames.put(293, "Picard");
		languageNames.put(294, "South_Saami");
		languageNames.put(295, "Võro");
		languageNames.put(296, "Kiche");
		languageNames.put(297, "Tabasco_Chontal");
		languageNames.put(298, "Chol");
		languageNames.put(299, "Chorti");
		languageNames.put(300, "Tzeltal");
		languageNames.put(301, "Tzotzil");
		languageNames.put(302, "Chicomuceltec");
		languageNames.put(303, "Huastec");
		languageNames.put(304, "Chuj");
		languageNames.put(305, "Tojolabal");
		languageNames.put(306, "Jakalteko");
		languageNames.put(307, "Kanjobal");
		languageNames.put(308, "Akateko");
		languageNames.put(309, "Mocho");
		languageNames.put(310, "Awakateko");
		languageNames.put(311, "Ixil");
		languageNames.put(312, "Mam");
		languageNames.put(313, "Tektiteko");
		languageNames.put(314, "Kekchí");
		languageNames.put(315, "Poqomam");
		languageNames.put(316, "Poqomchi");
		languageNames.put(317, "Kaqchikel");
		languageNames.put(318, "Achi");
		languageNames.put(319, "Tzutujil");
		languageNames.put(320, "Sacapulteco");
		languageNames.put(321, "Sipacapense");
		languageNames.put(322, "Uspanteco");
		languageNames.put(323, "Mopán_Maya");
		languageNames.put(324, "Lacandon");
		languageNames.put(325, "Yucatán_Maya");
		languageNames.put(327, "Middle_High_German");
		languageNames.put(328, "Old_High_German");
		languageNames.put(329, "Mongolian");
		languageNames.put(330, "Aceh");
		languageNames.put(331, "Rapa_Nui");
		languageNames.put(332, "Old_French");
		languageNames.put(333, "Middle_French");
		languageNames.put(334, "Haitian_Creole_French");
		languageNames.put(335, "Church_Slavic");
		languageNames.put(336, "Latgalian");
		languageNames.put(337, "Aramaic_Official_Hebrew");
		languageNames.put(338, "Aramaic_Jewish_Palestinian");
		languageNames.put(339, "Classical_Syriac");
		languageNames.put(340, "Jewish_Babylonian_Aramaic");
		languageNames.put(341, "Hiligaynon");
		languageNames.put(342, "Old_Irish");
		languageNames.put(343, "Karachay_Balkar");
		languageNames.put(344, "Réunion_Creole");
		languageNames.put(345, "Benga");
		languageNames.put(346, "Punu");
		languageNames.put(347, "Mpongwe");
		languageNames.put(348, "Kélé");
		languageNames.put(349, "Chewa");
		languageNames.put(350, "Bemba");
		languageNames.put(351, "Umbundu");
		languageNames.put(352, "Lunda");
		languageNames.put(353, "Tonga");
		languageNames.put(354, "Albanian");
		languageNames.put(355, "Sesotho");
		languageNames.put(356, "Kalaallisut");
		languageNames.put(357, "Northern_Kurdish");
		languageNames.put(358, "Kabuverdianu");
		languageNames.put(359, "Ugaritic");
		languageNames.put(360, "Vlax_Romani");
		languageNames.put(361, "Classical_Armenian");
		languageNames.put(362, "Ottoman_Turkish");
		languageNames.put(363, "Abi");
		languageNames.put(364, "Araki");
		languageNames.put(365, "Bislama");
		languageNames.put(366, "Fon");
		languageNames.put(367, "Futunan");
		languageNames.put(368, "International");
		languageNames.put(369, "Holikachuk");
		languageNames.put(370, "Uzbek");
		languageNames.put(371, "Anglo_Norman");
		languageNames.put(372, "Bainouk_Gunyaamolo");
		languageNames.put(373, "Greek_Ancient_Egypt");
		languageNames.put(374, "Malagasy");
		languageNames.put(375, "Tsimihety_Malagasy");
		return languageNames.get(i);
	}

	public static String getISO639_3(int i)
	{
		languageNames.put(84,"bul");
		languageNames.put(85,"eng");
		languageNames.put(86,"fra");
		languageNames.put(87,"spa");
		languageNames.put(88,"rus");
		languageNames.put(89,"nld");
		languageNames.put(90,"ces");
		languageNames.put(91,"swe");
		languageNames.put(92,"slv");
		languageNames.put(93,"pol");
		languageNames.put(94,"por");
		languageNames.put(95,"nob");
		languageNames.put(96,"eus");
		languageNames.put(97,"slk");
		languageNames.put(98,"est");
		languageNames.put(99,"fin");
		languageNames.put(100,"ita");
		languageNames.put(101,"deu");
		languageNames.put(102,"hun");
		languageNames.put(103,"dan");
		languageNames.put(104,"eng-US");
		languageNames.put(105,"ell");
		languageNames.put(106,"heb");
		languageNames.put(107,"cmn-Hans");
		languageNames.put(109,"nap");
		languageNames.put(110,"mar");
		languageNames.put(111,"lmo");
		languageNames.put(112,"jpn");
		languageNames.put(113,"epo");
		languageNames.put(114,"pms");
		languageNames.put(115,"vec");
		languageNames.put(116,"ukr");
		languageNames.put(117,"cat");
		languageNames.put(118,"ewe");
		languageNames.put(119,"aka");
		languageNames.put(120,"arb");
		languageNames.put(121,"hau-Arab");
		languageNames.put(122,"hau-Latn");
		languageNames.put(123,"hye");
		languageNames.put(124,"kat");
		languageNames.put(125,"afr");
		languageNames.put(126,"fra-CA");
		languageNames.put(127,"fra-CH");
		languageNames.put(128,"srp-Cyrl");
		languageNames.put(129,"srp-Latn");
		languageNames.put(130,"tha");
		languageNames.put(131,"ido");
		languageNames.put(133,"ron");
		languageNames.put(134,"ksh");
		languageNames.put(135,"cmn-Hant");
		languageNames.put(136,"eng-UK");
		languageNames.put(137,"tur");
		languageNames.put(138,"kor");
		languageNames.put(139,"khm");
		languageNames.put(140,"scn");
		languageNames.put(141,"arg");
		languageNames.put(142,"pes");
		languageNames.put(143,"lav");
		languageNames.put(144,"vie");
		languageNames.put(145,"swh");
		languageNames.put(146,"bar");
		languageNames.put(147,"bel");
		languageNames.put(148,"csb");
		languageNames.put(149,"hrv");
		languageNames.put(150,"lit");
		languageNames.put(151,"yue");
		languageNames.put(152,"tgk");
		languageNames.put(153,"cym");
		languageNames.put(154,"bam");
		languageNames.put(155,"por-BR");
		languageNames.put(156,"por-PT");
		languageNames.put(158,"tel");
		languageNames.put(159,"glk");
		languageNames.put(160,"mhr");
		languageNames.put(161,"mrj");
		languageNames.put(162,"guj");
		languageNames.put(163,"hin");
		languageNames.put(164,"tam");
		languageNames.put(165,"ind");
		languageNames.put(166,"gle");
		languageNames.put(167,"fra-BE");
		languageNames.put(168,"lim");
		languageNames.put(169,"gsw");
		languageNames.put(170,"rwr");
		languageNames.put(171,"srn");
		languageNames.put(172,"deu-AT");
		languageNames.put(173,"deu-CH");
		languageNames.put(174,"grc");
		languageNames.put(175,"gmy");
		languageNames.put(176,"cpg");
		languageNames.put(177,"als");
		languageNames.put(178,"aln");
		languageNames.put(179,"aat");
		languageNames.put(180,"aae");
		languageNames.put(181,"kan");
		languageNames.put(182,"bre");
		languageNames.put(183,"fri");
		languageNames.put(184,"nav");
		languageNames.put(185,"ben");
		languageNames.put(186,"urd");
		languageNames.put(187,"fra-FR");
		languageNames.put(188,"nep");
		languageNames.put(189,"ibo");
		languageNames.put(190,"lld");
		languageNames.put(191,"kaz");
		languageNames.put(192,"wln");
		languageNames.put(193,"isl");
		languageNames.put(194,"tat");
		languageNames.put(195,"ast");
		languageNames.put(196,"snd-Arab");
		languageNames.put(197,"snd-Guru");
		languageNames.put(198,"yor");
		languageNames.put(199,"glg");
		languageNames.put(200,"nno");
		languageNames.put(202,"lin");
		languageNames.put(203,"xho");
		languageNames.put(204,"hsb");
		languageNames.put(205,"dsb");
		languageNames.put(206,"tgl");
		languageNames.put(207,"mlt");
		languageNames.put(208,"ceb");
		languageNames.put(209,"mkd");
		languageNames.put(210,"ina");
		languageNames.put(211,"ile");
		languageNames.put(213,"fao");
		languageNames.put(214,"zul");
		languageNames.put(215,"san");
		languageNames.put(216,"new");
		languageNames.put(217,"mal");
		languageNames.put(218,"vls");
		languageNames.put(219,"cic");
		languageNames.put(220,"cos");
		languageNames.put(221,"vol");
		languageNames.put(222,"mly");
		languageNames.put(223,"kab");
		languageNames.put(224,"glv");
		languageNames.put(225,"oss");
		languageNames.put(226,"crh");
		languageNames.put(227,"bak");
		languageNames.put(228,"chr");
		languageNames.put(229,"kir");
		languageNames.put(230,"gil");
		languageNames.put(231,"jav");
		languageNames.put(232,"ext");
		languageNames.put(233,"tet");
		languageNames.put(234,"mwl");
		languageNames.put(235,"eml");
		languageNames.put(236,"wol");
		languageNames.put(237,"som");
		languageNames.put(238,"lat");
		languageNames.put(239,"nov");
		languageNames.put(240,"ydd");
		languageNames.put(241,"pjt");
		languageNames.put(242,"jbo");
		languageNames.put(243,"ltz");
		languageNames.put(244,"roh");
		languageNames.put(245,"xmf");
		languageNames.put(246,"mri");
		languageNames.put(247,"kaa");
		languageNames.put(248,"div");
		languageNames.put(249,"asm");
		languageNames.put(250,"abk");
		languageNames.put(251,"avk");
		languageNames.put(252,"sun");
		languageNames.put(253,"cor");
		languageNames.put(254,"pdc");
		languageNames.put(255,"swb");
		languageNames.put(256,"stq");
		languageNames.put(257,"lug");
		languageNames.put(258,"sin");
		languageNames.put(259,"bpy");
		languageNames.put(260,"ckb");
		languageNames.put(261,"tir");
		languageNames.put(262,"gla");
		languageNames.put(263,"ang");
		languageNames.put(264,"dzo");
		languageNames.put(265,"lfn");
		languageNames.put(266,"yrl");
		languageNames.put(267,"szl");
		languageNames.put(268,"ruq");
		languageNames.put(269,"inh");
		languageNames.put(270,"bcc");
		languageNames.put(271,"myv");
		languageNames.put(272,"lao");
		languageNames.put(273,"oci");
		languageNames.put(274,"lij");
		languageNames.put(275,"mya");
		languageNames.put(276,"amh");
		languageNames.put(277,"mdf");
		languageNames.put(278,"ilo");
		languageNames.put(279,"chv");
		languageNames.put(280,"smo");
		languageNames.put(281,"udm");
		languageNames.put(282,"tpi");
		languageNames.put(283,"frp");
		languageNames.put(284,"sco");
		languageNames.put(285,"wym");
		languageNames.put(286,"haw");
		languageNames.put(287,"che");
		languageNames.put(288,"bos");
		languageNames.put(289,"ton");
		languageNames.put(290,"bqi");
		languageNames.put(291,"pnt");
		languageNames.put(292,"arz");
		languageNames.put(293,"pcd");
		languageNames.put(294,"sma");
		languageNames.put(295,"vro");
		languageNames.put(296,"quc");
		languageNames.put(297,"chf");
		languageNames.put(298,"ctu");
		languageNames.put(299,"caa");
		languageNames.put(300,"tzh");
		languageNames.put(301,"tzo");
		languageNames.put(302,"cob");
		languageNames.put(303,"hus");
		languageNames.put(304,"cac");
		languageNames.put(305,"toj");
		languageNames.put(306,"jac");
		languageNames.put(307,"kjb");
		languageNames.put(308,"knj");
		languageNames.put(309,"mhc");
		languageNames.put(310,"agu");
		languageNames.put(311,"ixl");
		languageNames.put(312,"mam");
		languageNames.put(313,"ttc");
		languageNames.put(314,"kek");
		languageNames.put(315,"poc");
		languageNames.put(316,"poh");
		languageNames.put(317,"cak");
		languageNames.put(318,"acr");
		languageNames.put(319,"tzj");
		languageNames.put(320,"quv");
		languageNames.put(321,"qum");
		languageNames.put(322,"usp");
		languageNames.put(323,"mop");
		languageNames.put(324,"lac");
		languageNames.put(325,"yua");
		languageNames.put(327,"gmh");
		languageNames.put(328,"goh");
		languageNames.put(329,"khk");
		languageNames.put(330,"ace");
		languageNames.put(331,"rap");
		languageNames.put(332,"fro");
		languageNames.put(333,"frm");
		languageNames.put(334,"hat");
		languageNames.put(335,"chu");
		languageNames.put(336,"ltg");
		languageNames.put(337,"arc-heb");
		languageNames.put(338,"jpa");
		languageNames.put(339,"syc");
		languageNames.put(340,"tmr");
		languageNames.put(341,"hil");
		languageNames.put(342,"sga");
		languageNames.put(343,"krc");
		languageNames.put(344,"rcf");
		languageNames.put(345,"bng");
		languageNames.put(346,"puu");
		languageNames.put(347,"mye-mpo");
		languageNames.put(348,"keb");
		languageNames.put(349,"nya");
		languageNames.put(350,"bem");
		languageNames.put(351,"umb");
		languageNames.put(352,"lun");
		languageNames.put(353,"toi");
		languageNames.put(354,"sqi");
		languageNames.put(355,"sot");
		languageNames.put(356,"kal");
		languageNames.put(357,"kmr");
		languageNames.put(358,"kea");
		languageNames.put(359,"uga");
		languageNames.put(360,"rmy");
		languageNames.put(361,"xcl");
		languageNames.put(362,"ota");
		languageNames.put(363,"aba");
		languageNames.put(364,"akr");
		languageNames.put(365,"bis");
		languageNames.put(366,"fon");
		languageNames.put(367,"fud");
		languageNames.put(368,"mul");
		languageNames.put(369,"hoi");
		languageNames.put(370,"uzb");
		languageNames.put(371,"xno");
		languageNames.put(372,"bcz");
		languageNames.put(373,"grc-x-LXX");
		languageNames.put(374,"mlg");
		languageNames.put(375,"xmw");
		return languageNames.get(i);
	}


}
